//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.27 at 02:03:14 PM EDT 
//


package ebay.apis.eblbasecomponents;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				This is the base response type of the <b>GetItemsAwaitingFeedback</b> call. This call retrieves all completed order line items for which the user (buyer or seller) still needs to leave Feedback for their order partner.
 * 			
 * 
 * <p>Java class for GetItemsAwaitingFeedbackResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetItemsAwaitingFeedbackResponseType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:ebay:apis:eBLBaseComponents}AbstractResponseType">
 *       &lt;sequence>
 *         &lt;element name="ItemsAwaitingFeedback" type="{urn:ebay:apis:eBLBaseComponents}PaginatedTransactionArrayType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetItemsAwaitingFeedbackResponseType", propOrder = {
    "itemsAwaitingFeedback"
})
public class GetItemsAwaitingFeedbackResponseType
    extends AbstractResponseType
{

    @XmlElement(name = "ItemsAwaitingFeedback")
    protected PaginatedTransactionArrayType itemsAwaitingFeedback;

    /**
     * Gets the value of the itemsAwaitingFeedback property.
     * 
     * @return
     *     possible object is
     *     {@link PaginatedTransactionArrayType }
     *     
     */
    public PaginatedTransactionArrayType getItemsAwaitingFeedback() {
        return itemsAwaitingFeedback;
    }

    /**
     * Sets the value of the itemsAwaitingFeedback property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaginatedTransactionArrayType }
     *     
     */
    public void setItemsAwaitingFeedback(PaginatedTransactionArrayType value) {
        this.itemsAwaitingFeedback = value;
    }

}
