//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.27 at 02:03:14 PM EDT 
//


package ebay.apis.eblbasecomponents;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				The base response to a <b>GetSellingManagerSaleRecord</b> call.
 * 			
 * 
 * <p>Java class for GetSellingManagerSaleRecordResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetSellingManagerSaleRecordResponseType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:ebay:apis:eBLBaseComponents}AbstractResponseType">
 *       &lt;sequence>
 *         &lt;element name="SellingManagerSoldOrder" type="{urn:ebay:apis:eBLBaseComponents}SellingManagerSoldOrderType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetSellingManagerSaleRecordResponseType", propOrder = {
    "sellingManagerSoldOrder"
})
public class GetSellingManagerSaleRecordResponseType
    extends AbstractResponseType
{

    @XmlElement(name = "SellingManagerSoldOrder")
    protected SellingManagerSoldOrderType sellingManagerSoldOrder;

    /**
     * Gets the value of the sellingManagerSoldOrder property.
     * 
     * @return
     *     possible object is
     *     {@link SellingManagerSoldOrderType }
     *     
     */
    public SellingManagerSoldOrderType getSellingManagerSoldOrder() {
        return sellingManagerSoldOrder;
    }

    /**
     * Sets the value of the sellingManagerSoldOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link SellingManagerSoldOrderType }
     *     
     */
    public void setSellingManagerSoldOrder(SellingManagerSoldOrderType value) {
        this.sellingManagerSoldOrder = value;
    }

}
