//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.27 at 02:03:14 PM EDT 
//


package ebay.apis.eblbasecomponents;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				This type provides information about the domestic leg of a Global Shipping Program shipment.
 * 				<br/><br/>
 * 				<span class="tablenote">
 * 				<strong>Note:</strong> The <strong>LogisticsProviderShipmentToBuyer</strong> field is reserved for the exclusive use of the international shipping provider.
 * 				</span>
 * 			
 * 
 * <p>Java class for MultiLegShippingDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MultiLegShippingDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SellerShipmentToLogisticsProvider" type="{urn:ebay:apis:eBLBaseComponents}MultiLegShipmentType" minOccurs="0"/>
 *         &lt;element name="LogisticsProviderShipmentToBuyer" type="{urn:ebay:apis:eBLBaseComponents}MultiLegShipmentType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MultiLegShippingDetailsType", propOrder = {
    "sellerShipmentToLogisticsProvider",
    "logisticsProviderShipmentToBuyer"
})
public class MultiLegShippingDetailsType {

    @XmlElement(name = "SellerShipmentToLogisticsProvider")
    protected MultiLegShipmentType sellerShipmentToLogisticsProvider;
    @XmlElement(name = "LogisticsProviderShipmentToBuyer")
    protected MultiLegShipmentType logisticsProviderShipmentToBuyer;

    /**
     * Gets the value of the sellerShipmentToLogisticsProvider property.
     * 
     * @return
     *     possible object is
     *     {@link MultiLegShipmentType }
     *     
     */
    public MultiLegShipmentType getSellerShipmentToLogisticsProvider() {
        return sellerShipmentToLogisticsProvider;
    }

    /**
     * Sets the value of the sellerShipmentToLogisticsProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiLegShipmentType }
     *     
     */
    public void setSellerShipmentToLogisticsProvider(MultiLegShipmentType value) {
        this.sellerShipmentToLogisticsProvider = value;
    }

    /**
     * Gets the value of the logisticsProviderShipmentToBuyer property.
     * 
     * @return
     *     possible object is
     *     {@link MultiLegShipmentType }
     *     
     */
    public MultiLegShipmentType getLogisticsProviderShipmentToBuyer() {
        return logisticsProviderShipmentToBuyer;
    }

    /**
     * Sets the value of the logisticsProviderShipmentToBuyer property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiLegShipmentType }
     *     
     */
    public void setLogisticsProviderShipmentToBuyer(MultiLegShipmentType value) {
        this.logisticsProviderShipmentToBuyer = value;
    }

}
