//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.27 at 02:03:14 PM EDT 
//


package ebay.apis.eblbasecomponents;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 * 				This type defines the <b>PaymentHoldDetails</b> container, which
 * 				consists of information related to the payment hold on the order, including the
 * 				reason why the buyer's payment for the order is being held, the expected
 * 				release date of the funds into the seller's account, and possible action(s) the
 * 				seller can take to expedite the payout of funds into their account.
 * 			
 * 
 * <p>Java class for PaymentHoldDetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PaymentHoldDetailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ExpectedReleaseDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="RequiredSellerActionArray" type="{urn:ebay:apis:eBLBaseComponents}RequiredSellerActionArrayType" minOccurs="0"/>
 *         &lt;element name="NumOfReqSellerActions" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="PaymentHoldReason" type="{urn:ebay:apis:eBLBaseComponents}PaymentHoldReasonCodeType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentHoldDetailType", propOrder = {
    "expectedReleaseDate",
    "requiredSellerActionArray",
    "numOfReqSellerActions",
    "paymentHoldReason"
})
public class PaymentHoldDetailType {

    @XmlElement(name = "ExpectedReleaseDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar expectedReleaseDate;
    @XmlElement(name = "RequiredSellerActionArray")
    protected RequiredSellerActionArrayType requiredSellerActionArray;
    @XmlElement(name = "NumOfReqSellerActions")
    protected Integer numOfReqSellerActions;
    @XmlElement(name = "PaymentHoldReason")
    @XmlSchemaType(name = "token")
    protected PaymentHoldReasonCodeType paymentHoldReason;

    /**
     * Gets the value of the expectedReleaseDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpectedReleaseDate() {
        return expectedReleaseDate;
    }

    /**
     * Sets the value of the expectedReleaseDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpectedReleaseDate(XMLGregorianCalendar value) {
        this.expectedReleaseDate = value;
    }

    /**
     * Gets the value of the requiredSellerActionArray property.
     * 
     * @return
     *     possible object is
     *     {@link RequiredSellerActionArrayType }
     *     
     */
    public RequiredSellerActionArrayType getRequiredSellerActionArray() {
        return requiredSellerActionArray;
    }

    /**
     * Sets the value of the requiredSellerActionArray property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequiredSellerActionArrayType }
     *     
     */
    public void setRequiredSellerActionArray(RequiredSellerActionArrayType value) {
        this.requiredSellerActionArray = value;
    }

    /**
     * Gets the value of the numOfReqSellerActions property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumOfReqSellerActions() {
        return numOfReqSellerActions;
    }

    /**
     * Sets the value of the numOfReqSellerActions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumOfReqSellerActions(Integer value) {
        this.numOfReqSellerActions = value;
    }

    /**
     * Gets the value of the paymentHoldReason property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentHoldReasonCodeType }
     *     
     */
    public PaymentHoldReasonCodeType getPaymentHoldReason() {
        return paymentHoldReason;
    }

    /**
     * Sets the value of the paymentHoldReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentHoldReasonCodeType }
     *     
     */
    public void setPaymentHoldReason(PaymentHoldReasonCodeType value) {
        this.paymentHoldReason = value;
    }

}
