//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.27 at 02:03:14 PM EDT 
//


package ebay.apis.eblbasecomponents;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProductRequiredCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ProductRequiredCodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Disabled"/>
 *     &lt;enumeration value="Enabled"/>
 *     &lt;enumeration value="CustomCode"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ProductRequiredCodeType")
@XmlEnum
public enum ProductRequiredCodeType {


    /**
     * 
     * 						If this enumeration value is returned for a brand, the eBay seller is not required to use an eBay catalog product when creating or revising their listing in this category for this product brand. Although not required, the seller will still have an option to use an eBay catalog product if one exists for their product.
     * 						<br/><br/>
     * 						<span class="tablenote"><b>Note: </b> For more information about the Product-Based Shopping Experience requirement, see the <a href="https://developer.ebay.com/api-docs/sell/static/inventory/pbse_playbook_intro.html" target="_blank">Product-Based Shopping Experience Playbook</a>.
     * 						</span>
     * 					
     * 
     */
    @XmlEnumValue("Disabled")
    DISABLED("Disabled"),

    /**
     * 
     * 						If this enumeration value is returned, the eBay seller is required to use an eBay catalog product when creating or revising their listing in this category for this product brand. A listing can be associated with an eBay catalog product by using the Add/Revise/Relist calls. For complete information on how to create or revise a listing using a eBay catalog product, see the <a href="https://developer.ebay.com/api-docs/sell/static/inventory/pbse-phase2-trading-workflows.html#" target="_blank">Phase 2 recommended workflows using Trading API</a> topic in the <b>Product-Based Shopping Experience Playbook</b>.
     * 					
     * 
     */
    @XmlEnumValue("Enabled")
    ENABLED("Enabled"),

    /**
     * 
     * 						(out) Reserved for internal or future use.
     * 				  
     * 
     */
    @XmlEnumValue("CustomCode")
    CUSTOM_CODE("CustomCode");
    private final String value;

    ProductRequiredCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ProductRequiredCodeType fromValue(String v) {
        for (ProductRequiredCodeType c: ProductRequiredCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
