//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.27 at 02:03:14 PM EDT 
//


package ebay.apis.eblbasecomponents;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Indicates category support for listing of Local Market items by sellers
 * 				subscribed to Local Market for Regular Vehicles.
 * 				Each of the subscriptions will have following options, which will define
 * 				"National" vs "Local" ad format listing.
 * 				"LocalOptional" : This will allow national and local listing.
 * 				"LocalOnly" : Seller can have Local listings only.
 * 				"NationalOnly" : Seller can not opt into local only exposure. It has to be
 * 				national listing.
 * 			
 * 
 * <p>Java class for RegularSubscriptionDefinitionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegularSubscriptionDefinitionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegularSubscriptionDefinitionType")
public class RegularSubscriptionDefinitionType {


}
